//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AlgoSdk.Kmd
{
    
    
    public partial struct InitWalletHandleTokenResponse
    {
        
        private static bool @__generated__IsValid = InitWalletHandleTokenResponse.@__generated__InitializeAlgoApiFormatters();
        
        private static bool @__generated__InitializeAlgoApiFormatters()
        {
            AlgoSdk.AlgoApiFormatterLookup.Add<AlgoSdk.Kmd.InitWalletHandleTokenResponse>(new AlgoSdk.AlgoApiObjectFormatter<AlgoSdk.Kmd.InitWalletHandleTokenResponse>(false).Assign("wallet_handle_token", (AlgoSdk.Kmd.InitWalletHandleTokenResponse x) => x.WalletHandleToken, (ref AlgoSdk.Kmd.InitWalletHandleTokenResponse x, Unity.Collections.FixedString128Bytes value) => x.WalletHandleToken = value).Assign("error", (AlgoSdk.Kmd.InitWalletHandleTokenResponse x) => x.Error, (ref AlgoSdk.Kmd.InitWalletHandleTokenResponse x, AlgoSdk.Optional<System.Boolean> value) => x.Error = value).Assign("message", (AlgoSdk.Kmd.InitWalletHandleTokenResponse x) => x.Message, (ref AlgoSdk.Kmd.InitWalletHandleTokenResponse x, System.String value) => x.Message = value, AlgoSdk.StringComparer.Instance));
            return true;
        }
    }
}
