//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AlgoSdk.Kmd
{
    
    
    public partial struct ReleaseWalletHandleTokenRequest
    {
        
        private static bool @__generated__IsValid = ReleaseWalletHandleTokenRequest.@__generated__InitializeAlgoApiFormatters();
        
        private static bool @__generated__InitializeAlgoApiFormatters()
        {
            AlgoSdk.AlgoApiFormatterLookup.Add<AlgoSdk.Kmd.ReleaseWalletHandleTokenRequest>(new AlgoSdk.AlgoApiObjectFormatter<AlgoSdk.Kmd.ReleaseWalletHandleTokenRequest>(false).Assign("wallet_handle_token", (AlgoSdk.Kmd.ReleaseWalletHandleTokenRequest x) => x.WalletHandleToken, (ref AlgoSdk.Kmd.ReleaseWalletHandleTokenRequest x, Unity.Collections.FixedString128Bytes value) => x.WalletHandleToken = value));
            return true;
        }
    }
}
