//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AlgoSdk.Kmd
{
    
    
    public partial struct SignTransactionRequest
    {
        
        private static bool @__generated__IsValid = SignTransactionRequest.@__generated__InitializeAlgoApiFormatters();
        
        private static bool @__generated__InitializeAlgoApiFormatters()
        {
            AlgoSdk.AlgoApiFormatterLookup.Add<AlgoSdk.Kmd.SignTransactionRequest>(new AlgoSdk.AlgoApiObjectFormatter<AlgoSdk.Kmd.SignTransactionRequest>(false).Assign("public_key", (AlgoSdk.Kmd.SignTransactionRequest x) => x.PublicKey, (ref AlgoSdk.Kmd.SignTransactionRequest x, AlgoSdk.Crypto.Ed25519.PublicKey value) => x.PublicKey = value).Assign("transaction", (AlgoSdk.Kmd.SignTransactionRequest x) => x.Transaction, (ref AlgoSdk.Kmd.SignTransactionRequest x, System.Byte[] value) => x.Transaction = value, AlgoSdk.ArrayComparer<System.Byte>.Instance).Assign("wallet_handle_token", (AlgoSdk.Kmd.SignTransactionRequest x) => x.WalletHandleToken, (ref AlgoSdk.Kmd.SignTransactionRequest x, Unity.Collections.FixedString128Bytes value) => x.WalletHandleToken = value).Assign("wallet_password", (AlgoSdk.Kmd.SignTransactionRequest x) => x.WalletPassword, (ref AlgoSdk.Kmd.SignTransactionRequest x, Unity.Collections.FixedString128Bytes value) => x.WalletPassword = value));
            return true;
        }
    }
}
