//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AlgoSdk.Kmd
{
    
    
    public partial struct SignProgramRequest
    {
        
        private static bool @__generated__IsValid = SignProgramRequest.@__generated__InitializeAlgoApiFormatters();
        
        private static bool @__generated__InitializeAlgoApiFormatters()
        {
            AlgoSdk.AlgoApiFormatterLookup.Add<AlgoSdk.Kmd.SignProgramRequest>(new AlgoSdk.AlgoApiObjectFormatter<AlgoSdk.Kmd.SignProgramRequest>(false).Assign("address", (AlgoSdk.Kmd.SignProgramRequest x) => x.Address, (ref AlgoSdk.Kmd.SignProgramRequest x, AlgoSdk.Address value) => x.Address = value).Assign("data", (AlgoSdk.Kmd.SignProgramRequest x) => x.Data, (ref AlgoSdk.Kmd.SignProgramRequest x, System.Byte[] value) => x.Data = value, AlgoSdk.ArrayComparer<System.Byte>.Instance).Assign("wallet_handle_token", (AlgoSdk.Kmd.SignProgramRequest x) => x.WalletHandleToken, (ref AlgoSdk.Kmd.SignProgramRequest x, Unity.Collections.FixedString128Bytes value) => x.WalletHandleToken = value).Assign("wallet_password", (AlgoSdk.Kmd.SignProgramRequest x) => x.WalletPassword, (ref AlgoSdk.Kmd.SignProgramRequest x, Unity.Collections.FixedString128Bytes value) => x.WalletPassword = value));
            return true;
        }
    }
}
