//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AlgoSdk.Kmd
{
    
    
    public partial struct SignMultisigResponse
    {
        
        private static bool @__generated__IsValid = SignMultisigResponse.@__generated__InitializeAlgoApiFormatters();
        
        private static bool @__generated__InitializeAlgoApiFormatters()
        {
            AlgoSdk.AlgoApiFormatterLookup.Add<AlgoSdk.Kmd.SignMultisigResponse>(new AlgoSdk.AlgoApiObjectFormatter<AlgoSdk.Kmd.SignMultisigResponse>(false).Assign("multisig", (AlgoSdk.Kmd.SignMultisigResponse x) => x.SignedTransaction, (ref AlgoSdk.Kmd.SignMultisigResponse x, System.Byte[] value) => x.SignedTransaction = value, AlgoSdk.ArrayComparer<System.Byte>.Instance).Assign("error", (AlgoSdk.Kmd.SignMultisigResponse x) => x.Error, (ref AlgoSdk.Kmd.SignMultisigResponse x, AlgoSdk.Optional<System.Boolean> value) => x.Error = value).Assign("message", (AlgoSdk.Kmd.SignMultisigResponse x) => x.Message, (ref AlgoSdk.Kmd.SignMultisigResponse x, System.String value) => x.Message = value, AlgoSdk.StringComparer.Instance));
            return true;
        }
    }
}
