//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AlgoSdk
{
    
    
    public partial struct StateProofTrackingDataMap
    {
        
        private static bool @__generated__IsValid = StateProofTrackingDataMap.@__generated__InitializeAlgoApiFormatters();
        
        private static bool @__generated__InitializeAlgoApiFormatters()
        {
            AlgoSdk.AlgoApiFormatterLookup.Add<AlgoSdk.StateProofTrackingDataMap>(new AlgoSdk.AlgoApiObjectFormatter<AlgoSdk.StateProofTrackingDataMap>(false).Assign("0", (AlgoSdk.StateProofTrackingDataMap x) => x.StateProofBasicData, (ref AlgoSdk.StateProofTrackingDataMap x, AlgoSdk.StateProofTrackingData value) => x.StateProofBasicData = value));
            return true;
        }
    }
}
