//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AlgoSdk.Kmd
{
    
    
    public partial struct WalletInfoResponse
    {
        
        private static bool @__generated__IsValid = WalletInfoResponse.@__generated__InitializeAlgoApiFormatters();
        
        private static bool @__generated__InitializeAlgoApiFormatters()
        {
            AlgoSdk.AlgoApiFormatterLookup.Add<AlgoSdk.Kmd.WalletInfoResponse>(new AlgoSdk.AlgoApiObjectFormatter<AlgoSdk.Kmd.WalletInfoResponse>(false).Assign("wallet_handle", (AlgoSdk.Kmd.WalletInfoResponse x) => x.WalletHandle, (ref AlgoSdk.Kmd.WalletInfoResponse x, AlgoSdk.Kmd.WalletHandle value) => x.WalletHandle = value).Assign("error", (AlgoSdk.Kmd.WalletInfoResponse x) => x.Error, (ref AlgoSdk.Kmd.WalletInfoResponse x, AlgoSdk.Optional<System.Boolean> value) => x.Error = value).Assign("message", (AlgoSdk.Kmd.WalletInfoResponse x) => x.Message, (ref AlgoSdk.Kmd.WalletInfoResponse x, System.String value) => x.Message = value, AlgoSdk.StringComparer.Instance));
            return true;
        }
    }
}
