//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AlgoSdk.Kmd
{
    
    
    public partial struct Wallet
    {
        
        private static bool @__generated__IsValid = Wallet.@__generated__InitializeAlgoApiFormatters();
        
        private static bool @__generated__InitializeAlgoApiFormatters()
        {
            AlgoSdk.AlgoApiFormatterLookup.Add<AlgoSdk.Kmd.Wallet>(new AlgoSdk.AlgoApiObjectFormatter<AlgoSdk.Kmd.Wallet>(false).Assign("driver_name", (AlgoSdk.Kmd.Wallet x) => x.DriverName, (ref AlgoSdk.Kmd.Wallet x, Unity.Collections.FixedString64Bytes value) => x.DriverName = value).Assign("driver_version", (AlgoSdk.Kmd.Wallet x) => x.DriverVersion, (ref AlgoSdk.Kmd.Wallet x, System.UInt32 value) => x.DriverVersion = value).Assign("id", (AlgoSdk.Kmd.Wallet x) => x.Id, (ref AlgoSdk.Kmd.Wallet x, Unity.Collections.FixedString128Bytes value) => x.Id = value).Assign("mnemonic_ux", (AlgoSdk.Kmd.Wallet x) => x.MnemonicUx, (ref AlgoSdk.Kmd.Wallet x, AlgoSdk.Optional<System.Boolean> value) => x.MnemonicUx = value).Assign("name", (AlgoSdk.Kmd.Wallet x) => x.Name, (ref AlgoSdk.Kmd.Wallet x, Unity.Collections.FixedString64Bytes value) => x.Name = value).Assign("supported_txs", (AlgoSdk.Kmd.Wallet x) => x.SupportedTransactions, (ref AlgoSdk.Kmd.Wallet x, AlgoSdk.TransactionType[] value) => x.SupportedTransactions = value, AlgoSdk.ArrayComparer<AlgoSdk.TransactionType, AlgoSdk.ByteEnumComparer<AlgoSdk.TransactionType>>.Instance));
            return true;
        }
    }
}
