//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AlgoSdk
{


    public partial struct AlgoApiObject
    {

        private static bool @__generated__IsValid = AlgoApiObject.@__generated__InitializeAlgoApiFormatters();

        private static bool @__generated__InitializeAlgoApiFormatters()
        {
            AlgoSdk.AlgoApiFormatterLookup.Add<AlgoSdk.AlgoApiObject>(new AlgoSdk.AlgoApiObjectFormatter());
            AlgoSdk.AlgoApiFormatterLookup.Add<AlgoSdk.AlgoApiObject[]>(AlgoSdk.Formatters.ArrayFormatter<AlgoSdk.AlgoApiObject>.Instance);
            return true;
        }
    }
}
