//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AlgoSdk
{
    
    
    public partial struct InitWalletHandleTokenResponse
    {
        
        private static bool @__generated__IsValid = InitWalletHandleTokenResponse.@__generated__InitializeAlgoApiFormatters();
        
        private static bool @__generated__InitializeAlgoApiFormatters()
        {
            AlgoSdk.AlgoApiFormatterLookup.Add<AlgoSdk.InitWalletHandleTokenResponse>(new AlgoSdk.AlgoApiObjectFormatter<AlgoSdk.InitWalletHandleTokenResponse>().Assign("wallet_handle_token", null, (AlgoSdk.InitWalletHandleTokenResponse x) => x.WalletHandleToken, (ref AlgoSdk.InitWalletHandleTokenResponse x, Unity.Collections.FixedString128Bytes value) => x.WalletHandleToken = value, false).Assign("error", null, (AlgoSdk.InitWalletHandleTokenResponse x) => x.Error, (ref AlgoSdk.InitWalletHandleTokenResponse x, AlgoSdk.Optional<System.Boolean> value) => x.Error = value, false).Assign("message", null, (AlgoSdk.InitWalletHandleTokenResponse x) => x.Message, (ref AlgoSdk.InitWalletHandleTokenResponse x, System.String value) => x.Message = value, AlgoSdk.StringComparer.Instance, false));
            return true;
        }
    }
}
