//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AlgoSdk
{
    
    
    public partial struct VrfPubKey
    {
        
        private static bool @__generated__IsValid = VrfPubKey.@__generated__InitializeAlgoApiFormatters();
        
        private static bool @__generated__InitializeAlgoApiFormatters()
        {
            AlgoSdk.AlgoApiFormatterLookup.Add<AlgoSdk.VrfPubKey>(new AlgoSdk.Formatters.ByteArrayFormatter<AlgoSdk.VrfPubKey>());
            return true;
        }
    }
}
