//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AlgoSdk.Kmd
{
    
    
    public partial struct SignMultisigRequest
    {
        
        private static bool @__generated__IsValid = SignMultisigRequest.@__generated__InitializeAlgoApiFormatters();
        
        private static bool @__generated__InitializeAlgoApiFormatters()
        {
            AlgoSdk.AlgoApiFormatterLookup.Add<AlgoSdk.Kmd.SignMultisigRequest>(new AlgoSdk.AlgoApiObjectFormatter<AlgoSdk.Kmd.SignMultisigRequest>(false).Assign("partial_multisig", (AlgoSdk.Kmd.SignMultisigRequest x) => x.Multisig, (ref AlgoSdk.Kmd.SignMultisigRequest x, AlgoSdk.Multisig value) => x.Multisig = value).Assign("public_key", (AlgoSdk.Kmd.SignMultisigRequest x) => x.PublicKey, (ref AlgoSdk.Kmd.SignMultisigRequest x, AlgoSdk.Crypto.Ed25519.PublicKey value) => x.PublicKey = value).Assign("signer", (AlgoSdk.Kmd.SignMultisigRequest x) => x.Signer, (ref AlgoSdk.Kmd.SignMultisigRequest x, AlgoSdk.Address value) => x.Signer = value).Assign("transaction", (AlgoSdk.Kmd.SignMultisigRequest x) => x.Transaction, (ref AlgoSdk.Kmd.SignMultisigRequest x, System.Byte[] value) => x.Transaction = value, AlgoSdk.ArrayComparer<System.Byte>.Instance).Assign("wallet_handle_token", (AlgoSdk.Kmd.SignMultisigRequest x) => x.WalletHandleToken, (ref AlgoSdk.Kmd.SignMultisigRequest x, Unity.Collections.FixedString128Bytes value) => x.WalletHandleToken = value).Assign("wallet_password", (AlgoSdk.Kmd.SignMultisigRequest x) => x.WalletPassword, (ref AlgoSdk.Kmd.SignMultisigRequest x, Unity.Collections.FixedString128Bytes value) => x.WalletPassword = value));
            return true;
        }
    }
}
