//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AlgoSdk.Kmd
{
    
    
    public partial struct SignProgramMultisigResponse
    {
        
        private static bool @__generated__IsValid = SignProgramMultisigResponse.@__generated__InitializeAlgoApiFormatters();
        
        private static bool @__generated__InitializeAlgoApiFormatters()
        {
            AlgoSdk.AlgoApiFormatterLookup.Add<AlgoSdk.Kmd.SignProgramMultisigResponse>(new AlgoSdk.AlgoApiObjectFormatter<AlgoSdk.Kmd.SignProgramMultisigResponse>(false).Assign("multisig", (AlgoSdk.Kmd.SignProgramMultisigResponse x) => x.SignedProgram, (ref AlgoSdk.Kmd.SignProgramMultisigResponse x, System.Byte[] value) => x.SignedProgram = value, AlgoSdk.ArrayComparer<System.Byte>.Instance).Assign("error", (AlgoSdk.Kmd.SignProgramMultisigResponse x) => x.Error, (ref AlgoSdk.Kmd.SignProgramMultisigResponse x, AlgoSdk.Optional<System.Boolean> value) => x.Error = value).Assign("message", (AlgoSdk.Kmd.SignProgramMultisigResponse x) => x.Message, (ref AlgoSdk.Kmd.SignProgramMultisigResponse x, System.String value) => x.Message = value, AlgoSdk.StringComparer.Instance));
            return true;
        }
    }
}
