//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AlgoSdk.Kmd
{
    
    
    public partial struct SignProgramMultisigRequest
    {
        
        private static bool @__generated__IsValid = SignProgramMultisigRequest.@__generated__InitializeAlgoApiFormatters();
        
        private static bool @__generated__InitializeAlgoApiFormatters()
        {
            AlgoSdk.AlgoApiFormatterLookup.Add<AlgoSdk.Kmd.SignProgramMultisigRequest>(new AlgoSdk.AlgoApiObjectFormatter<AlgoSdk.Kmd.SignProgramMultisigRequest>(false).Assign("address", (AlgoSdk.Kmd.SignProgramMultisigRequest x) => x.Address, (ref AlgoSdk.Kmd.SignProgramMultisigRequest x, AlgoSdk.Address value) => x.Address = value).Assign("data", (AlgoSdk.Kmd.SignProgramMultisigRequest x) => x.Data, (ref AlgoSdk.Kmd.SignProgramMultisigRequest x, System.Byte[] value) => x.Data = value, AlgoSdk.ArrayComparer<System.Byte>.Instance).Assign("partial_multisig", (AlgoSdk.Kmd.SignProgramMultisigRequest x) => x.Multisig, (ref AlgoSdk.Kmd.SignProgramMultisigRequest x, AlgoSdk.Multisig value) => x.Multisig = value).Assign("public_key", (AlgoSdk.Kmd.SignProgramMultisigRequest x) => x.PublicKey, (ref AlgoSdk.Kmd.SignProgramMultisigRequest x, AlgoSdk.Crypto.Ed25519.PublicKey value) => x.PublicKey = value).Assign("wallet_handle_token", (AlgoSdk.Kmd.SignProgramMultisigRequest x) => x.WalletHandleToken, (ref AlgoSdk.Kmd.SignProgramMultisigRequest x, Unity.Collections.FixedString128Bytes value) => x.WalletHandleToken = value).Assign("wallet_password", (AlgoSdk.Kmd.SignProgramMultisigRequest x) => x.WalletPassword, (ref AlgoSdk.Kmd.SignProgramMultisigRequest x, Unity.Collections.FixedString128Bytes value) => x.WalletPassword = value));
            return true;
        }
    }
}
