//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AlgoSdk
{
    
    
    public partial struct ApplicationsResponse
    {
        
        private static bool @__generated__IsValid = ApplicationsResponse.@__generated__InitializeAlgoApiFormatters();
        
        private static bool @__generated__InitializeAlgoApiFormatters()
        {
            AlgoSdk.AlgoApiFormatterLookup.Add<AlgoSdk.ApplicationsResponse>(new AlgoSdk.AlgoApiObjectFormatter<AlgoSdk.ApplicationsResponse>(false).Assign("applications", (AlgoSdk.ApplicationsResponse x) => x.Applications, (ref AlgoSdk.ApplicationsResponse x, AlgoSdk.Application[] value) => x.Applications = value, AlgoSdk.ArrayComparer<AlgoSdk.Application>.Instance).Assign("current-round", (AlgoSdk.ApplicationsResponse x) => x.CurrentRound, (ref AlgoSdk.ApplicationsResponse x, System.UInt64 value) => x.CurrentRound = value).Assign("next-token", (AlgoSdk.ApplicationsResponse x) => x.NextToken, (ref AlgoSdk.ApplicationsResponse x, Unity.Collections.FixedString128Bytes value) => x.NextToken = value));
            return true;
        }
    }
}
