//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AlgoSdk
{
    
    
    public partial struct Hex
    {
        
        private static bool @__generated__IsValid = Hex.@__generated__InitializeAlgoApiFormatters();
        
        private static bool @__generated__InitializeAlgoApiFormatters()
        {
            AlgoSdk.AlgoApiFormatterLookup.Add<AlgoSdk.Hex>(new AlgoSdk.Formatters.HexFormatter());
            AlgoSdk.AlgoApiFormatterLookup.Add<AlgoSdk.Hex[]>(AlgoSdk.Formatters.ArrayFormatter<AlgoSdk.Hex>.Instance);
            return true;
        }
    }
}
