//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AlgoSdk
{
    
    
    public partial struct AppEvalDelta<TTxn>
    {
        
        private static bool @__generated__IsValid = AppEvalDelta<TTxn>.@__generated__InitializeAlgoApiFormatters();
        
        private static bool @__generated__InitializeAlgoApiFormatters()
        {
            AlgoSdk.AlgoApiFormatterLookup.Add<AlgoSdk.AppEvalDelta<TTxn>>(new AlgoSdk.AlgoApiObjectFormatter<AlgoSdk.AppEvalDelta<TTxn>>(false).Assign("gd", (AlgoSdk.AppEvalDelta<TTxn> x) => x.GlobalDelta, (ref AlgoSdk.AppEvalDelta<TTxn> x, AlgoSdk.AppStateDelta value) => x.GlobalDelta = value).Assign("ld", (AlgoSdk.AppEvalDelta<TTxn> x) => x.LocalDeltas, (ref AlgoSdk.AppEvalDelta<TTxn> x, AlgoSdk.AccountStateDelta[] value) => x.LocalDeltas = value, AlgoSdk.ArrayComparer<AlgoSdk.AccountStateDelta>.Instance).Assign("lg", (AlgoSdk.AppEvalDelta<TTxn> x) => x.Logs, (ref AlgoSdk.AppEvalDelta<TTxn> x, System.String[] value) => x.Logs = value, AlgoSdk.ArrayComparer<System.String, AlgoSdk.StringComparer>.Instance).Assign("itx", (AlgoSdk.AppEvalDelta<TTxn> x) => x.InnerTxns, (ref AlgoSdk.AppEvalDelta<TTxn> x, TTxn[] value) => x.InnerTxns = value, AlgoSdk.ArrayComparer<TTxn>.Instance));
            return true;
        }
    }
}
