//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AlgoSdk
{
    
    
    public partial struct SignedTransaction
    {
        
        private static bool @__generated__IsValid = SignedTransaction.@__generated__InitializeAlgoApiFormatters();
        
        private static bool @__generated__InitializeAlgoApiFormatters()
        {
            AlgoSdk.AlgoApiFormatterLookup.Add<AlgoSdk.SignedTransaction>(new AlgoSdk.Formatters.SignedTransactionFormatter());
            AlgoSdk.AlgoApiFormatterLookup.Add<AlgoSdk.SignedTransaction[]>(AlgoSdk.Formatters.ArrayFormatter<AlgoSdk.SignedTransaction>.Instance);
            return true;
        }
    }
}
