//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using UnityCollections = Unity.Collections;


namespace Algorand.Unity.WalletConnect
{
    
    
    public partial struct JsonRpcResponse
    {
        
        private static bool @__generated__IsValid = JsonRpcResponse.@__generated__InitializeAlgoApiFormatters();
        
        private static bool @__generated__InitializeAlgoApiFormatters()
        {
            Algorand.Unity.AlgoApiFormatterLookup.Add<Algorand.Unity.WalletConnect.JsonRpcResponse>(new Algorand.Unity.AlgoApiObjectFormatter<Algorand.Unity.WalletConnect.JsonRpcResponse>(true).Assign("id", (Algorand.Unity.WalletConnect.JsonRpcResponse x) => x.Id, (ref Algorand.Unity.WalletConnect.JsonRpcResponse x, Algorand.Unity.Optional<System.UInt64> value) => x.Id = value).Assign("jsonrpc", (Algorand.Unity.WalletConnect.JsonRpcResponse x) => x.JsonRpc, (ref Algorand.Unity.WalletConnect.JsonRpcResponse x, System.String value) => x.JsonRpc = value, Algorand.Unity.StringComparer.Instance).Assign("result", (Algorand.Unity.WalletConnect.JsonRpcResponse x) => x.Result, (ref Algorand.Unity.WalletConnect.JsonRpcResponse x, Algorand.Unity.AlgoApiObject value) => x.Result = value).Assign("error", (Algorand.Unity.WalletConnect.JsonRpcResponse x) => x.Error, (ref Algorand.Unity.WalletConnect.JsonRpcResponse x, Algorand.Unity.WalletConnect.JsonRpcError value) => x.Error = value));
            return true;
        }
    }
}
