//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using UnityCollections = Unity.Collections;


namespace Algorand.Unity.WalletConnect
{
    
    
    public partial struct SignTxnsError
    {
        
        private static bool @__generated__IsValid = SignTxnsError.@__generated__InitializeAlgoApiFormatters();
        
        private static bool @__generated__InitializeAlgoApiFormatters()
        {
            Algorand.Unity.AlgoApiFormatterLookup.Add<Algorand.Unity.WalletConnect.SignTxnsError>(new Algorand.Unity.AlgoApiObjectFormatter<Algorand.Unity.WalletConnect.SignTxnsError>(false).Assign("message", (Algorand.Unity.WalletConnect.SignTxnsError x) => x.Message, (ref Algorand.Unity.WalletConnect.SignTxnsError x, System.String value) => x.Message = value, Algorand.Unity.StringComparer.Instance).Assign("code", (Algorand.Unity.WalletConnect.SignTxnsError x) => x.Code, (ref Algorand.Unity.WalletConnect.SignTxnsError x, System.Int32 value) => x.Code = value).Assign("data", (Algorand.Unity.WalletConnect.SignTxnsError x) => x.Data, (ref Algorand.Unity.WalletConnect.SignTxnsError x, Algorand.Unity.AlgoApiObject value) => x.Data = value));
            return true;
        }
    }
}
