//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using UnityCollections = Unity.Collections;


namespace Algorand.Unity.WalletConnect
{
    
    
    public partial struct WalletConnectSessionData
    {
        
        private static bool @__generated__IsValid = WalletConnectSessionData.@__generated__InitializeAlgoApiFormatters();
        
        private static bool @__generated__InitializeAlgoApiFormatters()
        {
            Algorand.Unity.AlgoApiFormatterLookup.Add<Algorand.Unity.WalletConnect.WalletConnectSessionData>(new Algorand.Unity.AlgoApiObjectFormatter<Algorand.Unity.WalletConnect.WalletConnectSessionData>(false).Assign("peerId", (Algorand.Unity.WalletConnect.WalletConnectSessionData x) => x.PeerId, (ref Algorand.Unity.WalletConnect.WalletConnectSessionData x, System.String value) => x.PeerId = value, Algorand.Unity.StringComparer.Instance).Assign("peerMeta", (Algorand.Unity.WalletConnect.WalletConnectSessionData x) => x.PeerMeta, (ref Algorand.Unity.WalletConnect.WalletConnectSessionData x, Algorand.Unity.WalletConnect.ClientMeta value) => x.PeerMeta = value).Assign("approved", (Algorand.Unity.WalletConnect.WalletConnectSessionData x) => x.IsApproved, (ref Algorand.Unity.WalletConnect.WalletConnectSessionData x, System.Boolean value) => x.IsApproved = value).Assign("chainId", (Algorand.Unity.WalletConnect.WalletConnectSessionData x) => x.ChainId, (ref Algorand.Unity.WalletConnect.WalletConnectSessionData x, System.Int32 value) => x.ChainId = value).Assign("accounts", (Algorand.Unity.WalletConnect.WalletConnectSessionData x) => x.Accounts, (ref Algorand.Unity.WalletConnect.WalletConnectSessionData x, Algorand.Unity.Address[] value) => x.Accounts = value, Algorand.Unity.ArrayComparer<Algorand.Unity.Address>.Instance));
            return true;
        }
    }
}
