//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AlgoSdk
{
    
    
    public partial struct Sig
    {
        
        private static bool @__generated__IsValid = Sig.@__generated__InitializeAlgoApiFormatters();
        
        private static bool @__generated__InitializeAlgoApiFormatters()
        {
            AlgoSdk.AlgoApiFormatterLookup.AddFormatter(typeof(AlgoSdk.Sig), new AlgoSdk.Formatters.ByteArrayFormatter<AlgoSdk.Sig>());
            AlgoSdk.AlgoApiFormatterLookup.AddFormatter(typeof(AlgoSdk.Sig[]), AlgoSdk.Formatters.ArrayFormatter<AlgoSdk.Sig[]>.Instance);
            return true;
        }
    }
}
