//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AlgoSdk
{
    
    
    public partial struct ApplicationParams
    {
        
        private static bool @__generated__IsValid = ApplicationParams.@__generated__InitializeAlgoApiFormatters();
        
        private static bool @__generated__InitializeAlgoApiFormatters()
        {
            AlgoSdk.AlgoApiFormatterLookup.Add<AlgoSdk.ApplicationParams>(new AlgoSdk.AlgoApiObjectFormatter<AlgoSdk.ApplicationParams>().Assign("approval-program", null, (AlgoSdk.ApplicationParams x) => x.ApprovalProgram, (ref AlgoSdk.ApplicationParams x, AlgoSdk.CompiledTeal value) => x.ApprovalProgram = value, false).Assign("clear-state-program", null, (AlgoSdk.ApplicationParams x) => x.ClearStateProgram, (ref AlgoSdk.ApplicationParams x, AlgoSdk.CompiledTeal value) => x.ClearStateProgram = value, false).Assign("creator", null, (AlgoSdk.ApplicationParams x) => x.Creator, (ref AlgoSdk.ApplicationParams x, AlgoSdk.Address value) => x.Creator = value, false).Assign("extra-program-pages", null, (AlgoSdk.ApplicationParams x) => x.ExtraProgramPages, (ref AlgoSdk.ApplicationParams x, System.UInt64 value) => x.ExtraProgramPages = value, false).Assign("global-state", null, (AlgoSdk.ApplicationParams x) => x.GlobalState, (ref AlgoSdk.ApplicationParams x, AlgoSdk.TealKeyValue[] value) => x.GlobalState = value, AlgoSdk.ArrayComparer<AlgoSdk.TealKeyValue>.Instance, false).Assign("global-state-schema", null, (AlgoSdk.ApplicationParams x) => x.GlobalStateSchema, (ref AlgoSdk.ApplicationParams x, AlgoSdk.StateSchema value) => x.GlobalStateSchema = value, false).Assign("local-state-schema", null, (AlgoSdk.ApplicationParams x) => x.LocalStateSchema, (ref AlgoSdk.ApplicationParams x, AlgoSdk.StateSchema value) => x.LocalStateSchema = value, false));
            AlgoSdk.AlgoApiFormatterLookup.Add<AlgoSdk.ApplicationParams[]>(AlgoSdk.Formatters.ArrayFormatter<AlgoSdk.ApplicationParams>.Instance);
            return true;
        }
    }
}
