//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AlgoSdk
{
    
    
    public partial struct CompiledTeal
    {
        
        private static bool @__generated__IsValid = CompiledTeal.@__generated__InitializeAlgoApiFormatters();
        
        private static bool @__generated__InitializeAlgoApiFormatters()
        {
            AlgoSdk.AlgoApiFormatterLookup.AddFormatter(typeof(AlgoSdk.CompiledTeal), new AlgoSdk.CompiledTealFormatter());
            AlgoSdk.AlgoApiFormatterLookup.AddFormatter(typeof(AlgoSdk.CompiledTeal[]), AlgoSdk.Formatters.ArrayFormatter<AlgoSdk.CompiledTeal[]>.Instance);
            return true;
        }
    }
}
