//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AlgoSdk
{
    
    
    public partial struct TransactionsResponse
    {
        
        private static bool @__generated__IsValid = TransactionsResponse.@__generated__InitializeAlgoApiFormatters();
        
        private static bool @__generated__InitializeAlgoApiFormatters()
        {
            AlgoSdk.AlgoApiFormatterLookup.Add<AlgoSdk.TransactionsResponse>(new AlgoSdk.AlgoApiObjectFormatter<AlgoSdk.TransactionsResponse>(false).Assign("current-round", null, (AlgoSdk.TransactionsResponse x) => x.CurrentRound, (ref AlgoSdk.TransactionsResponse x, System.UInt64 value) => x.CurrentRound = value, false).Assign("next-token", null, (AlgoSdk.TransactionsResponse x) => x.NextToken, (ref AlgoSdk.TransactionsResponse x, Unity.Collections.FixedString128Bytes value) => x.NextToken = value, false).Assign("transactions", null, (AlgoSdk.TransactionsResponse x) => x.Transactions, (ref AlgoSdk.TransactionsResponse x, AlgoSdk.Transaction[] value) => x.Transactions = value, AlgoSdk.ArrayComparer<AlgoSdk.Transaction>.Instance, false));
            return true;
        }
    }
}
