//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AlgoSdk
{
    
    
    public partial struct SignProgramMultisigRequest
    {
        
        private static bool @__generated__IsValid = SignProgramMultisigRequest.@__generated__InitializeAlgoApiFormatters();
        
        private static bool @__generated__InitializeAlgoApiFormatters()
        {
            AlgoSdk.AlgoApiFormatterLookup.AddFormatter(typeof(AlgoSdk.SignProgramMultisigRequest), new AlgoSdk.AlgoApiObjectFormatter<AlgoSdk.SignProgramMultisigRequest>().Assign("address", null, (AlgoSdk.SignProgramMultisigRequest x) => x.Address, (ref AlgoSdk.SignProgramMultisigRequest x, AlgoSdk.Address value) => x.Address = value, false).Assign("data", null, (AlgoSdk.SignProgramMultisigRequest x) => x.Data, (ref AlgoSdk.SignProgramMultisigRequest x, System.Byte[] value) => x.Data = value, AlgoSdk.ArrayComparer<byte>.Instance, false).Assign("partial_multisig", null, (AlgoSdk.SignProgramMultisigRequest x) => x.Multisig, (ref AlgoSdk.SignProgramMultisigRequest x, AlgoSdk.Multisig value) => x.Multisig = value, false).Assign("public_key", null, (AlgoSdk.SignProgramMultisigRequest x) => x.PublicKey, (ref AlgoSdk.SignProgramMultisigRequest x, AlgoSdk.Crypto.Ed25519.PublicKey value) => x.PublicKey = value, false).Assign("wallet_handle_token", null, (AlgoSdk.SignProgramMultisigRequest x) => x.WalletHandleToken, (ref AlgoSdk.SignProgramMultisigRequest x, Unity.Collections.FixedString128Bytes value) => x.WalletHandleToken = value, false).Assign("wallet_password", null, (AlgoSdk.SignProgramMultisigRequest x) => x.WalletPassword, (ref AlgoSdk.SignProgramMultisigRequest x, Unity.Collections.FixedString128Bytes value) => x.WalletPassword = value, false));
            AlgoSdk.AlgoApiFormatterLookup.AddFormatter(typeof(AlgoSdk.SignProgramMultisigRequest[]), AlgoSdk.Formatters.ArrayFormatter<AlgoSdk.SignProgramMultisigRequest[]>.Instance);
            return true;
        }
    }
}
