//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AlgoSdk
{
    
    
    public partial struct GenerateKeyResponse
    {
        
        private static bool @__generated__IsValid = GenerateKeyResponse.@__generated__InitializeAlgoApiFormatters();
        
        private static bool @__generated__InitializeAlgoApiFormatters()
        {
            AlgoSdk.AlgoApiFormatterLookup.Add<AlgoSdk.GenerateKeyResponse>(new AlgoSdk.AlgoApiObjectFormatter<AlgoSdk.GenerateKeyResponse>(false).Assign("address", (AlgoSdk.GenerateKeyResponse x) => x.Address, (ref AlgoSdk.GenerateKeyResponse x, AlgoSdk.Address value) => x.Address = value).Assign("error", (AlgoSdk.GenerateKeyResponse x) => x.Error, (ref AlgoSdk.GenerateKeyResponse x, AlgoSdk.Optional<System.Boolean> value) => x.Error = value).Assign("message", (AlgoSdk.GenerateKeyResponse x) => x.Message, (ref AlgoSdk.GenerateKeyResponse x, System.String value) => x.Message = value, AlgoSdk.StringComparer.Instance));
            return true;
        }
    }
}
