//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using UnityCollections = Unity.Collections;


namespace Algorand.Unity
{
    
    
    public partial struct AssetParams
    {
        
        private static bool @__generated__IsValid = AssetParams.@__generated__InitializeAlgoApiFormatters();
        
        private static bool @__generated__InitializeAlgoApiFormatters()
        {
            Algorand.Unity.AlgoApiFormatterLookup.Add<Algorand.Unity.AssetParams>(new Algorand.Unity.AlgoApiObjectFormatter<Algorand.Unity.AssetParams>(false).Assign("c", (Algorand.Unity.AssetParams x) => x.Clawback, (ref Algorand.Unity.AssetParams x, Algorand.Unity.Address value) => x.Clawback = value).Assign("dc", (Algorand.Unity.AssetParams x) => x.Decimals, (ref Algorand.Unity.AssetParams x, System.UInt32 value) => x.Decimals = value).Assign("df", (Algorand.Unity.AssetParams x) => x.DefaultFrozen, (ref Algorand.Unity.AssetParams x, System.Boolean value) => x.DefaultFrozen = value).Assign("f", (Algorand.Unity.AssetParams x) => x.Freeze, (ref Algorand.Unity.AssetParams x, Algorand.Unity.Address value) => x.Freeze = value).Assign("m", (Algorand.Unity.AssetParams x) => x.Manager, (ref Algorand.Unity.AssetParams x, Algorand.Unity.Address value) => x.Manager = value).Assign("am", (Algorand.Unity.AssetParams x) => x.MetadataHash, (ref Algorand.Unity.AssetParams x, Algorand.Unity.Crypto.Sha512_256_Hash value) => x.MetadataHash = value).Assign("an", (Algorand.Unity.AssetParams x) => x.Name, (ref Algorand.Unity.AssetParams x, UnityCollections.FixedString64Bytes value) => x.Name = value).Assign("r", (Algorand.Unity.AssetParams x) => x.Reserve, (ref Algorand.Unity.AssetParams x, Algorand.Unity.Address value) => x.Reserve = value).Assign("t", (Algorand.Unity.AssetParams x) => x.Total, (ref Algorand.Unity.AssetParams x, System.UInt64 value) => x.Total = value).Assign("un", (Algorand.Unity.AssetParams x) => x.UnitName, (ref Algorand.Unity.AssetParams x, UnityCollections.FixedString32Bytes value) => x.UnitName = value).Assign("au", (Algorand.Unity.AssetParams x) => x.Url, (ref Algorand.Unity.AssetParams x, UnityCollections.FixedString128Bytes value) => x.Url = value));
            return true;
        }
    }
}
