//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using UnityCollections = Unity.Collections;


namespace Algorand.Unity
{
    
    
    public partial struct BlockRewards
    {
        
        private static bool @__generated__IsValid = BlockRewards.@__generated__InitializeAlgoApiFormatters();
        
        private static bool @__generated__InitializeAlgoApiFormatters()
        {
            Algorand.Unity.AlgoApiFormatterLookup.Add<Algorand.Unity.BlockRewards>(new Algorand.Unity.AlgoApiObjectFormatter<Algorand.Unity.BlockRewards>(false).Assign("fee-sink", (Algorand.Unity.BlockRewards x) => x.FeeSink, (ref Algorand.Unity.BlockRewards x, Algorand.Unity.Address value) => x.FeeSink = value).Assign("rewards-calculation-round", (Algorand.Unity.BlockRewards x) => x.RewardsCalculationRound, (ref Algorand.Unity.BlockRewards x, System.UInt64 value) => x.RewardsCalculationRound = value).Assign("rewards-level", (Algorand.Unity.BlockRewards x) => x.RewardsLevel, (ref Algorand.Unity.BlockRewards x, System.UInt64 value) => x.RewardsLevel = value).Assign("rewards-pool", (Algorand.Unity.BlockRewards x) => x.RewardsPool, (ref Algorand.Unity.BlockRewards x, Algorand.Unity.Address value) => x.RewardsPool = value).Assign("rewards-rate", (Algorand.Unity.BlockRewards x) => x.RewardsRate, (ref Algorand.Unity.BlockRewards x, System.UInt64 value) => x.RewardsRate = value).Assign("rewards-residue", (Algorand.Unity.BlockRewards x) => x.RewardsResidue, (ref Algorand.Unity.BlockRewards x, System.UInt64 value) => x.RewardsResidue = value));
            return true;
        }
    }
}
