//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using UnityCollections = Unity.Collections;


namespace Algorand.Unity
{
    
    
    public partial struct BoxRef
    {
        
        private static bool @__generated__IsValid = BoxRef.@__generated__InitializeAlgoApiFormatters();
        
        private static bool @__generated__InitializeAlgoApiFormatters()
        {
            Algorand.Unity.AlgoApiFormatterLookup.Add<Algorand.Unity.BoxRef>(new Algorand.Unity.AlgoApiObjectFormatter<Algorand.Unity.BoxRef>(false).Assign("i", (Algorand.Unity.BoxRef x) => x.Index, (ref Algorand.Unity.BoxRef x, System.UInt64 value) => x.Index = value).Assign("n", (Algorand.Unity.BoxRef x) => x.NameBytes, (ref Algorand.Unity.BoxRef x, System.Byte[] value) => x.NameBytes = value, Algorand.Unity.ArrayComparer<System.Byte>.Instance));
            return true;
        }
    }
}
