//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using UnityCollections = Unity.Collections;


namespace Algorand.Unity.Kmd
{
    
    
    public partial struct CreateWalletRequest
    {
        
        private static bool @__generated__IsValid = CreateWalletRequest.@__generated__InitializeAlgoApiFormatters();
        
        private static bool @__generated__InitializeAlgoApiFormatters()
        {
            Algorand.Unity.AlgoApiFormatterLookup.Add<Algorand.Unity.Kmd.CreateWalletRequest>(new Algorand.Unity.AlgoApiObjectFormatter<Algorand.Unity.Kmd.CreateWalletRequest>(false).Assign("master_derivation_key", (Algorand.Unity.Kmd.CreateWalletRequest x) => x.MasterDerivationKey, (ref Algorand.Unity.Kmd.CreateWalletRequest x, Algorand.Unity.PrivateKey value) => x.MasterDerivationKey = value).Assign("wallet_driver_name", (Algorand.Unity.Kmd.CreateWalletRequest x) => x.WalletDriverName, (ref Algorand.Unity.Kmd.CreateWalletRequest x, UnityCollections.FixedString128Bytes value) => x.WalletDriverName = value).Assign("wallet_name", (Algorand.Unity.Kmd.CreateWalletRequest x) => x.WalletName, (ref Algorand.Unity.Kmd.CreateWalletRequest x, UnityCollections.FixedString128Bytes value) => x.WalletName = value).Assign("wallet_password", (Algorand.Unity.Kmd.CreateWalletRequest x) => x.WalletPassword, (ref Algorand.Unity.Kmd.CreateWalletRequest x, UnityCollections.FixedString128Bytes value) => x.WalletPassword = value));
            return true;
        }
    }
}
