//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using UnityCollections = Unity.Collections;


namespace Algorand.Unity.Kmd
{
    
    
    public partial struct ExportMasterKeyResponse
    {
        
        private static bool @__generated__IsValid = ExportMasterKeyResponse.@__generated__InitializeAlgoApiFormatters();
        
        private static bool @__generated__InitializeAlgoApiFormatters()
        {
            Algorand.Unity.AlgoApiFormatterLookup.Add<Algorand.Unity.Kmd.ExportMasterKeyResponse>(new Algorand.Unity.AlgoApiObjectFormatter<Algorand.Unity.Kmd.ExportMasterKeyResponse>(false).Assign("master_derivation_key", (Algorand.Unity.Kmd.ExportMasterKeyResponse x) => x.MasterDerivationKey, (ref Algorand.Unity.Kmd.ExportMasterKeyResponse x, Algorand.Unity.PrivateKey value) => x.MasterDerivationKey = value).Assign("error", (Algorand.Unity.Kmd.ExportMasterKeyResponse x) => x.Error, (ref Algorand.Unity.Kmd.ExportMasterKeyResponse x, Algorand.Unity.Optional<System.Boolean> value) => x.Error = value).Assign("message", (Algorand.Unity.Kmd.ExportMasterKeyResponse x) => x.Message, (ref Algorand.Unity.Kmd.ExportMasterKeyResponse x, System.String value) => x.Message = value, Algorand.Unity.StringComparer.Instance));
            return true;
        }
    }
}
