//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using UnityCollections = Unity.Collections;


namespace Algorand.Unity.Kmd
{
    
    
    public partial struct ImportKeyResponse
    {
        
        private static bool @__generated__IsValid = ImportKeyResponse.@__generated__InitializeAlgoApiFormatters();
        
        private static bool @__generated__InitializeAlgoApiFormatters()
        {
            Algorand.Unity.AlgoApiFormatterLookup.Add<Algorand.Unity.Kmd.ImportKeyResponse>(new Algorand.Unity.AlgoApiObjectFormatter<Algorand.Unity.Kmd.ImportKeyResponse>(false).Assign("address", (Algorand.Unity.Kmd.ImportKeyResponse x) => x.Address, (ref Algorand.Unity.Kmd.ImportKeyResponse x, Algorand.Unity.Address value) => x.Address = value).Assign("error", (Algorand.Unity.Kmd.ImportKeyResponse x) => x.Error, (ref Algorand.Unity.Kmd.ImportKeyResponse x, Algorand.Unity.Optional<System.Boolean> value) => x.Error = value).Assign("message", (Algorand.Unity.Kmd.ImportKeyResponse x) => x.Message, (ref Algorand.Unity.Kmd.ImportKeyResponse x, System.String value) => x.Message = value, Algorand.Unity.StringComparer.Instance));
            return true;
        }
    }
}
