//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using UnityCollections = Unity.Collections;


namespace Algorand.Unity
{
    
    
    public partial struct LogicSig
    {
        
        private static bool @__generated__IsValid = LogicSig.@__generated__InitializeAlgoApiFormatters();
        
        private static bool @__generated__InitializeAlgoApiFormatters()
        {
            Algorand.Unity.AlgoApiFormatterLookup.Add<Algorand.Unity.LogicSig>(new Algorand.Unity.AlgoApiObjectFormatter<Algorand.Unity.LogicSig>(false).Assign("l", (Algorand.Unity.LogicSig x) => x.Program, (ref Algorand.Unity.LogicSig x, System.Byte[] value) => x.Program = value, Algorand.Unity.ArrayComparer<System.Byte>.Instance).Assign("arg", (Algorand.Unity.LogicSig x) => x.Args, (ref Algorand.Unity.LogicSig x, UnityCollections.FixedList128Bytes<System.Byte>[] value) => x.Args = value, Algorand.Unity.ArrayComparer<UnityCollections.FixedList128Bytes<System.Byte>>.Instance).Assign("sig", (Algorand.Unity.LogicSig x) => x.Sig, (ref Algorand.Unity.LogicSig x, Algorand.Unity.Sig value) => x.Sig = value).Assign("msig", (Algorand.Unity.LogicSig x) => x.Multisig, (ref Algorand.Unity.LogicSig x, Algorand.Unity.MultisigSig value) => x.Multisig = value));
            return true;
        }
    }
}
