//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using UnityCollections = Unity.Collections;


namespace Algorand.Unity.Kmd
{
    
    
    public partial struct RenameWalletRequest
    {
        
        private static bool @__generated__IsValid = RenameWalletRequest.@__generated__InitializeAlgoApiFormatters();
        
        private static bool @__generated__InitializeAlgoApiFormatters()
        {
            Algorand.Unity.AlgoApiFormatterLookup.Add<Algorand.Unity.Kmd.RenameWalletRequest>(new Algorand.Unity.AlgoApiObjectFormatter<Algorand.Unity.Kmd.RenameWalletRequest>(false).Assign("wallet_id", (Algorand.Unity.Kmd.RenameWalletRequest x) => x.WalletId, (ref Algorand.Unity.Kmd.RenameWalletRequest x, UnityCollections.FixedString128Bytes value) => x.WalletId = value).Assign("wallet_name", (Algorand.Unity.Kmd.RenameWalletRequest x) => x.WalletName, (ref Algorand.Unity.Kmd.RenameWalletRequest x, UnityCollections.FixedString128Bytes value) => x.WalletName = value).Assign("wallet_password", (Algorand.Unity.Kmd.RenameWalletRequest x) => x.WalletPassword, (ref Algorand.Unity.Kmd.RenameWalletRequest x, UnityCollections.FixedString128Bytes value) => x.WalletPassword = value));
            return true;
        }
    }
}
