//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using UnityCollections = Unity.Collections;


namespace Algorand.Unity.Kmd
{
    
    
    public partial struct SignProgramMultisigRequest
    {
        
        private static bool @__generated__IsValid = SignProgramMultisigRequest.@__generated__InitializeAlgoApiFormatters();
        
        private static bool @__generated__InitializeAlgoApiFormatters()
        {
            Algorand.Unity.AlgoApiFormatterLookup.Add<Algorand.Unity.Kmd.SignProgramMultisigRequest>(new Algorand.Unity.AlgoApiObjectFormatter<Algorand.Unity.Kmd.SignProgramMultisigRequest>(false).Assign("address", (Algorand.Unity.Kmd.SignProgramMultisigRequest x) => x.Address, (ref Algorand.Unity.Kmd.SignProgramMultisigRequest x, Algorand.Unity.Address value) => x.Address = value).Assign("data", (Algorand.Unity.Kmd.SignProgramMultisigRequest x) => x.Data, (ref Algorand.Unity.Kmd.SignProgramMultisigRequest x, System.Byte[] value) => x.Data = value, Algorand.Unity.ArrayComparer<System.Byte>.Instance).Assign("partial_multisig", (Algorand.Unity.Kmd.SignProgramMultisigRequest x) => x.Multisig, (ref Algorand.Unity.Kmd.SignProgramMultisigRequest x, Algorand.Unity.MultisigSig value) => x.Multisig = value).Assign("public_key", (Algorand.Unity.Kmd.SignProgramMultisigRequest x) => x.PublicKey, (ref Algorand.Unity.Kmd.SignProgramMultisigRequest x, Algorand.Unity.Crypto.Ed25519.PublicKey value) => x.PublicKey = value).Assign("wallet_handle_token", (Algorand.Unity.Kmd.SignProgramMultisigRequest x) => x.WalletHandleToken, (ref Algorand.Unity.Kmd.SignProgramMultisigRequest x, UnityCollections.FixedString128Bytes value) => x.WalletHandleToken = value).Assign("wallet_password", (Algorand.Unity.Kmd.SignProgramMultisigRequest x) => x.WalletPassword, (ref Algorand.Unity.Kmd.SignProgramMultisigRequest x, UnityCollections.FixedString128Bytes value) => x.WalletPassword = value));
            return true;
        }
    }
}
