//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using UnityCollections = Unity.Collections;


namespace Algorand.Unity
{
    
    
    public partial struct TealValue
    {
        
        private static bool @__generated__IsValid = TealValue.@__generated__InitializeAlgoApiFormatters();
        
        private static bool @__generated__InitializeAlgoApiFormatters()
        {
            Algorand.Unity.AlgoApiFormatterLookup.Add<Algorand.Unity.TealValue>(new Algorand.Unity.AlgoApiObjectFormatter<Algorand.Unity.TealValue>(false).Assign("tb", (Algorand.Unity.TealValue x) => x.Bytes, (ref Algorand.Unity.TealValue x, Algorand.Unity.TealBytes value) => x.Bytes = value).Assign("ui", (Algorand.Unity.TealValue x) => x.UintValue, (ref Algorand.Unity.TealValue x, System.UInt64 value) => x.UintValue = value).Assign("tt", (Algorand.Unity.TealValue x) => x.Type, (ref Algorand.Unity.TealValue x, Algorand.Unity.TealValueType value) => x.Type = value, Algorand.Unity.ByteEnumComparer<Algorand.Unity.TealValueType>.Instance));
            return true;
        }
    }
}
