//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using UnityCollections = Unity.Collections;


namespace Algorand.Unity
{
    
    
    public partial struct TransactionGroup
    {
        
        private static bool @__generated__IsValid = TransactionGroup.@__generated__InitializeAlgoApiFormatters();
        
        private static bool @__generated__InitializeAlgoApiFormatters()
        {
            Algorand.Unity.AlgoApiFormatterLookup.Add<Algorand.Unity.TransactionGroup>(new Algorand.Unity.AlgoApiObjectFormatter<Algorand.Unity.TransactionGroup>(false).Assign("txlist", (Algorand.Unity.TransactionGroup x) => x.Txns, (ref Algorand.Unity.TransactionGroup x, Algorand.Unity.TransactionId[] value) => x.Txns = value, Algorand.Unity.ArrayComparer<Algorand.Unity.TransactionId>.Instance));
            return true;
        }
    }
}
