//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using UnityCollections = Unity.Collections;


namespace Algorand.Unity
{
    
    
    public partial struct TransactionSignature
    {
        
        private static bool @__generated__IsValid = TransactionSignature.@__generated__InitializeAlgoApiFormatters();
        
        private static bool @__generated__InitializeAlgoApiFormatters()
        {
            Algorand.Unity.AlgoApiFormatterLookup.Add<Algorand.Unity.TransactionSignature>(new Algorand.Unity.AlgoApiObjectFormatter<Algorand.Unity.TransactionSignature>(false).Assign("logicsig", (Algorand.Unity.TransactionSignature x) => x.LogicSig, (ref Algorand.Unity.TransactionSignature x, Algorand.Unity.LogicSig value) => x.LogicSig = value).Assign("multisig", (Algorand.Unity.TransactionSignature x) => x.Multisig, (ref Algorand.Unity.TransactionSignature x, Algorand.Unity.MultisigSig value) => x.Multisig = value).Assign("sig", (Algorand.Unity.TransactionSignature x) => x.Sig, (ref Algorand.Unity.TransactionSignature x, Algorand.Unity.Sig value) => x.Sig = value));
            return true;
        }
    }
}
