//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using UnityCollections = Unity.Collections;


namespace Algorand.Unity
{
    
    
    public partial struct ValueDelta
    {
        
        private static bool @__generated__IsValid = ValueDelta.@__generated__InitializeAlgoApiFormatters();
        
        private static bool @__generated__InitializeAlgoApiFormatters()
        {
            Algorand.Unity.AlgoApiFormatterLookup.Add<Algorand.Unity.ValueDelta>(new Algorand.Unity.AlgoApiObjectFormatter<Algorand.Unity.ValueDelta>(false).Assign("at", (Algorand.Unity.ValueDelta x) => x.Action, (ref Algorand.Unity.ValueDelta x, Algorand.Unity.DeltaAction value) => x.Action = value, Algorand.Unity.ByteEnumComparer<Algorand.Unity.DeltaAction>.Instance).Assign("bs", (Algorand.Unity.ValueDelta x) => x.Bytes, (ref Algorand.Unity.ValueDelta x, Algorand.Unity.TealBytes value) => x.Bytes = value).Assign("ui", (Algorand.Unity.ValueDelta x) => x.UInt, (ref Algorand.Unity.ValueDelta x, System.UInt64 value) => x.UInt = value));
            return true;
        }
    }
}
