//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AlgoSdk
{
    
    
    public partial struct ApplicationParams
    {
        
        private static bool @__generated__IsValid = ApplicationParams.@__generated__InitializeAlgoApiFormatters();
        
        private static bool @__generated__InitializeAlgoApiFormatters()
        {
            AlgoSdk.AlgoApiFormatterLookup.Add<AlgoSdk.ApplicationParams>(new AlgoSdk.AlgoApiObjectFormatter<AlgoSdk.ApplicationParams>(false).Assign("approval-program", (AlgoSdk.ApplicationParams x) => x.ApprovalProgram, (ref AlgoSdk.ApplicationParams x, AlgoSdk.CompiledTeal value) => x.ApprovalProgram = value).Assign("clear-state-program", (AlgoSdk.ApplicationParams x) => x.ClearStateProgram, (ref AlgoSdk.ApplicationParams x, AlgoSdk.CompiledTeal value) => x.ClearStateProgram = value).Assign("creator", (AlgoSdk.ApplicationParams x) => x.Creator, (ref AlgoSdk.ApplicationParams x, AlgoSdk.Address value) => x.Creator = value).Assign("extra-program-pages", (AlgoSdk.ApplicationParams x) => x.ExtraProgramPages, (ref AlgoSdk.ApplicationParams x, System.UInt64 value) => x.ExtraProgramPages = value).Assign("global-state", (AlgoSdk.ApplicationParams x) => x.GlobalState, (ref AlgoSdk.ApplicationParams x, AlgoSdk.TealKeyValue[] value) => x.GlobalState = value, AlgoSdk.ArrayComparer<AlgoSdk.TealKeyValue>.Instance).Assign("global-state-schema", (AlgoSdk.ApplicationParams x) => x.GlobalStateSchema, (ref AlgoSdk.ApplicationParams x, AlgoSdk.StateSchema value) => x.GlobalStateSchema = value).Assign("local-state-schema", (AlgoSdk.ApplicationParams x) => x.LocalStateSchema, (ref AlgoSdk.ApplicationParams x, AlgoSdk.StateSchema value) => x.LocalStateSchema = value));
            return true;
        }
    }
}
