//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AlgoSdk
{
    
    
    public partial struct Application
    {
        
        private static bool @__generated__IsValid = Application.@__generated__InitializeAlgoApiFormatters();
        
        private static bool @__generated__InitializeAlgoApiFormatters()
        {
            AlgoSdk.AlgoApiFormatterLookup.Add<AlgoSdk.Application>(new AlgoSdk.AlgoApiObjectFormatter<AlgoSdk.Application>(false).Assign("created-at-round", (AlgoSdk.Application x) => x.CreatedAtRound, (ref AlgoSdk.Application x, System.UInt64 value) => x.CreatedAtRound = value).Assign("deleted", (AlgoSdk.Application x) => x.Deleted, (ref AlgoSdk.Application x, AlgoSdk.Optional<System.Boolean> value) => x.Deleted = value).Assign("deleted-at-round", (AlgoSdk.Application x) => x.DeletedAtRound, (ref AlgoSdk.Application x, System.UInt64 value) => x.DeletedAtRound = value).Assign("id", (AlgoSdk.Application x) => x.Id, (ref AlgoSdk.Application x, System.UInt64 value) => x.Id = value).Assign("params", (AlgoSdk.Application x) => x.Params, (ref AlgoSdk.Application x, AlgoSdk.ApplicationParams value) => x.Params = value));
            return true;
        }
    }
}
