//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AlgoSdk
{
    
    
    public partial struct Asset
    {
        
        private static bool @__generated__IsValid = Asset.@__generated__InitializeAlgoApiFormatters();
        
        private static bool @__generated__InitializeAlgoApiFormatters()
        {
            AlgoSdk.AlgoApiFormatterLookup.Add<AlgoSdk.Asset>(new AlgoSdk.AlgoApiObjectFormatter<AlgoSdk.Asset>(false).Assign("created-at-round", (AlgoSdk.Asset x) => x.CreatedAtRound, (ref AlgoSdk.Asset x, System.UInt64 value) => x.CreatedAtRound = value).Assign("deleted", (AlgoSdk.Asset x) => x.Deleted, (ref AlgoSdk.Asset x, AlgoSdk.Optional<System.Boolean> value) => x.Deleted = value).Assign("destroyed-at-round", (AlgoSdk.Asset x) => x.DestroyedAtRound, (ref AlgoSdk.Asset x, System.UInt64 value) => x.DestroyedAtRound = value).Assign("index", (AlgoSdk.Asset x) => x.Index, (ref AlgoSdk.Asset x, System.UInt64 value) => x.Index = value).Assign("params", (AlgoSdk.Asset x) => x.Params, (ref AlgoSdk.Asset x, AlgoSdk.AssetParams value) => x.Params = value));
            return true;
        }
    }
}
