//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AlgoSdk
{
    
    
    public partial struct AssetHolding
    {
        
        private static bool @__generated__IsValid = AssetHolding.@__generated__InitializeAlgoApiFormatters();
        
        private static bool @__generated__InitializeAlgoApiFormatters()
        {
            AlgoSdk.AlgoApiFormatterLookup.Add<AlgoSdk.AssetHolding>(new AlgoSdk.AlgoApiObjectFormatter<AlgoSdk.AssetHolding>(false).Assign("amount", (AlgoSdk.AssetHolding x) => x.Amount, (ref AlgoSdk.AssetHolding x, System.UInt64 value) => x.Amount = value).Assign("asset-id", (AlgoSdk.AssetHolding x) => x.AssetId, (ref AlgoSdk.AssetHolding x, System.UInt64 value) => x.AssetId = value).Assign("creator", (AlgoSdk.AssetHolding x) => x.Creator, (ref AlgoSdk.AssetHolding x, AlgoSdk.Address value) => x.Creator = value).Assign("deleted", (AlgoSdk.AssetHolding x) => x.Deleted, (ref AlgoSdk.AssetHolding x, AlgoSdk.Optional<System.Boolean> value) => x.Deleted = value).Assign("is-frozen", (AlgoSdk.AssetHolding x) => x.IsFrozen, (ref AlgoSdk.AssetHolding x, System.Boolean value) => x.IsFrozen = value).Assign("opted-in-at-round", (AlgoSdk.AssetHolding x) => x.OptedInAtRound, (ref AlgoSdk.AssetHolding x, System.UInt64 value) => x.OptedInAtRound = value).Assign("opted-out-at-round", (AlgoSdk.AssetHolding x) => x.OptedOutAtRound, (ref AlgoSdk.AssetHolding x, System.UInt64 value) => x.OptedOutAtRound = value));
            return true;
        }
    }
}
