//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AlgoSdk
{


    public partial struct GenerateKeyRequest
    {

        private static bool @__generated__IsValid = GenerateKeyRequest.@__generated__InitializeAlgoApiFormatters();

        private static bool @__generated__InitializeAlgoApiFormatters()
        {
            AlgoSdk.AlgoApiFormatterLookup.Add<AlgoSdk.GenerateKeyRequest>(new AlgoSdk.AlgoApiObjectFormatter<AlgoSdk.GenerateKeyRequest>().Assign("display_mnemonic", null, (AlgoSdk.GenerateKeyRequest x) => x.DisplayMnemonic, (ref AlgoSdk.GenerateKeyRequest x, AlgoSdk.Optional<System.Boolean> value) => x.DisplayMnemonic = value, false).Assign("wallet_handle_token", null, (AlgoSdk.GenerateKeyRequest x) => x.WalletHandleToken, (ref AlgoSdk.GenerateKeyRequest x, Unity.Collections.FixedString128Bytes value) => x.WalletHandleToken = value, false));
            AlgoSdk.AlgoApiFormatterLookup.Add<AlgoSdk.GenerateKeyRequest[]>(AlgoSdk.Formatters.ArrayFormatter<AlgoSdk.GenerateKeyRequest>.Instance);
            return true;
        }
    }
}
