//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using UnityCollections = Unity.Collections;


namespace Algorand.Unity.WalletConnect.Core
{
    
    
    public partial struct Metadata
    {
        
        private static bool @__generated__IsValid = Metadata.@__generated__InitializeAlgoApiFormatters();
        
        private static bool @__generated__InitializeAlgoApiFormatters()
        {
            Algorand.Unity.AlgoApiFormatterLookup.Add<Algorand.Unity.WalletConnect.Core.Metadata>(new Algorand.Unity.AlgoApiObjectFormatter<Algorand.Unity.WalletConnect.Core.Metadata>(false).Assign("name", (Algorand.Unity.WalletConnect.Core.Metadata x) => x.Name, (ref Algorand.Unity.WalletConnect.Core.Metadata x, System.String value) => x.Name = value, Algorand.Unity.StringComparer.Instance).Assign("description", (Algorand.Unity.WalletConnect.Core.Metadata x) => x.Description, (ref Algorand.Unity.WalletConnect.Core.Metadata x, System.String value) => x.Description = value, Algorand.Unity.StringComparer.Instance).Assign("url", (Algorand.Unity.WalletConnect.Core.Metadata x) => x.Url, (ref Algorand.Unity.WalletConnect.Core.Metadata x, System.String value) => x.Url = value, Algorand.Unity.StringComparer.Instance).Assign("icons", (Algorand.Unity.WalletConnect.Core.Metadata x) => x.Icons, (ref Algorand.Unity.WalletConnect.Core.Metadata x, System.String[] value) => x.Icons = value, Algorand.Unity.ArrayComparer<System.String, Algorand.Unity.StringComparer>.Instance).Assign("verifyUrl", (Algorand.Unity.WalletConnect.Core.Metadata x) => x.VerifyUrl, (ref Algorand.Unity.WalletConnect.Core.Metadata x, System.String value) => x.VerifyUrl = value, Algorand.Unity.StringComparer.Instance).Assign("redirect", (Algorand.Unity.WalletConnect.Core.Metadata x) => x.Redirect, (ref Algorand.Unity.WalletConnect.Core.Metadata x, Algorand.Unity.Optional<Algorand.Unity.WalletConnect.Core.Metadata.RedirectData> value) => x.Redirect = value));
            return true;
        }
        
        public partial struct RedirectData
        {
            
            private static bool @__generated__IsValid = RedirectData.@__generated__InitializeAlgoApiFormatters();
            
            private static bool @__generated__InitializeAlgoApiFormatters()
            {
                Algorand.Unity.AlgoApiFormatterLookup.Add<Algorand.Unity.WalletConnect.Core.Metadata.RedirectData>(new Algorand.Unity.AlgoApiObjectFormatter<Algorand.Unity.WalletConnect.Core.Metadata.RedirectData>(false).Assign("native", (Algorand.Unity.WalletConnect.Core.Metadata.RedirectData x) => x.Native, (ref Algorand.Unity.WalletConnect.Core.Metadata.RedirectData x, System.String value) => x.Native = value, Algorand.Unity.StringComparer.Instance).Assign("universal", (Algorand.Unity.WalletConnect.Core.Metadata.RedirectData x) => x.Universal, (ref Algorand.Unity.WalletConnect.Core.Metadata.RedirectData x, System.String value) => x.Universal = value, Algorand.Unity.StringComparer.Instance));
                return true;
            }
        }
    }
}
