//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using UnityCollections = Unity.Collections;


namespace Algorand.Unity.WalletConnect.Core
{
    
    
    public partial struct SessionProposeRequestPayload
    {
        
        private static bool @__generated__IsValid = SessionProposeRequestPayload.@__generated__InitializeAlgoApiFormatters();
        
        private static bool @__generated__InitializeAlgoApiFormatters()
        {
            Algorand.Unity.AlgoApiFormatterLookup.Add<Algorand.Unity.WalletConnect.Core.SessionProposeRequestPayload>(new Algorand.Unity.AlgoApiObjectFormatter<Algorand.Unity.WalletConnect.Core.SessionProposeRequestPayload>(false).Assign("relays", (Algorand.Unity.WalletConnect.Core.SessionProposeRequestPayload x) => x.Relays, (ref Algorand.Unity.WalletConnect.Core.SessionProposeRequestPayload x, Algorand.Unity.WalletConnect.Core.ProtocolOptions[] value) => x.Relays = value, Algorand.Unity.ArrayComparer<Algorand.Unity.WalletConnect.Core.ProtocolOptions>.Instance).Assign("requiredNamespaces", (Algorand.Unity.WalletConnect.Core.SessionProposeRequestPayload x) => x.RequiredNamespaces, (ref Algorand.Unity.WalletConnect.Core.SessionProposeRequestPayload x, Algorand.Unity.WalletConnect.Core.RequiredNamespaces value) => x.RequiredNamespaces = value).Assign("optionalNamespaces", (Algorand.Unity.WalletConnect.Core.SessionProposeRequestPayload x) => x.OptionalNamespaces, (ref Algorand.Unity.WalletConnect.Core.SessionProposeRequestPayload x, Algorand.Unity.WalletConnect.Core.OptionalNamespaces value) => x.OptionalNamespaces = value).Assign("session", (Algorand.Unity.WalletConnect.Core.SessionProposeRequestPayload x) => x.SessionProperties, (ref Algorand.Unity.WalletConnect.Core.SessionProposeRequestPayload x, Algorand.Unity.WalletConnect.Core.SessionProperties value) => x.SessionProperties = value).Assign("proposer", (Algorand.Unity.WalletConnect.Core.SessionProposeRequestPayload x) => x.Proposer, (ref Algorand.Unity.WalletConnect.Core.SessionProposeRequestPayload x, Algorand.Unity.WalletConnect.Core.Participant value) => x.Proposer = value));
            return true;
        }
    }
}

namespace Algorand.Unity.WalletConnect.Core
{
    
    
    public partial struct SessionProposeResponsePayload
    {
        
        private static bool @__generated__IsValid = SessionProposeResponsePayload.@__generated__InitializeAlgoApiFormatters();
        
        private static bool @__generated__InitializeAlgoApiFormatters()
        {
            Algorand.Unity.AlgoApiFormatterLookup.Add<Algorand.Unity.WalletConnect.Core.SessionProposeResponsePayload>(new Algorand.Unity.AlgoApiObjectFormatter<Algorand.Unity.WalletConnect.Core.SessionProposeResponsePayload>(false).Assign("relay", (Algorand.Unity.WalletConnect.Core.SessionProposeResponsePayload x) => x.Relay, (ref Algorand.Unity.WalletConnect.Core.SessionProposeResponsePayload x, Algorand.Unity.WalletConnect.Core.ProtocolOptions value) => x.Relay = value).Assign("responderPublicKey", (Algorand.Unity.WalletConnect.Core.SessionProposeResponsePayload x) => x.ResponderPublicKey, (ref Algorand.Unity.WalletConnect.Core.SessionProposeResponsePayload x, System.String value) => x.ResponderPublicKey = value, Algorand.Unity.StringComparer.Instance));
            return true;
        }
    }
}
