//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using UnityCollections = Unity.Collections;


namespace Algorand.Unity.WalletConnect.Core
{
    
    
    public partial struct SessionProperties
    {
        
        private static bool @__generated__IsValid = SessionProperties.@__generated__InitializeAlgoApiFormatters();
        
        private static bool @__generated__InitializeAlgoApiFormatters()
        {
            Algorand.Unity.AlgoApiFormatterLookup.Add<Algorand.Unity.WalletConnect.Core.SessionProperties>(new Algorand.Unity.AlgoApiObjectFormatter<Algorand.Unity.WalletConnect.Core.SessionProperties>(false));
            return true;
        }
    }
}
